<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[❌ Kajal Rokade shown in UI but NOT found in DB with role='user']]>
    </line>
  </reporter-output>
  <suite started-at="2025-06-27T17:09:05 IST" name="Default suite" finished-at="2025-06-27T17:09:12 IST" duration-ms="7175">
    <groups>
    </groups>
    <test started-at="2025-06-27T17:09:05 IST" name="Default test" finished-at="2025-06-27T17:09:12 IST" duration-ms="7175">
      <class name="validLoginTesting.UserValidation">
        <test-method is-config="true" signature="preCondition()[pri:0, instance:validLoginTesting.UserValidation@609cd4d8]" started-at="2025-06-27T17:09:05 IST" name="preCondition" finished-at="2025-06-27T17:09:10 IST" duration-ms="5858" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preCondition -->
        <test-method signature="allUsersValidation()[pri:2, instance:validLoginTesting.UserValidation@609cd4d8]" started-at="2025-06-27T17:09:10 IST" name="allUsersValidation" finished-at="2025-06-27T17:09:12 IST" duration-ms="1266" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Kajal Rokade is missing from DB or does not have role='user']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Kajal Rokade is missing from DB or does not have role='user'
at org.testng.Assert.fail(Assert.java:111)
at validLoginTesting.UserValidation.allUsersValidation(UserValidation.java:98)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[❌ Kajal Rokade shown in UI but NOT found in DB with role='user']]>
            </line>
          </reporter-output>
        </test-method> <!-- allUsersValidation -->
      </class> <!-- validLoginTesting.UserValidation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
